name = "sleep-mcp-server"
main = "dist/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
account_id = "d4ca2ffcbf66d256bb1d333e523c3a2f"

# KV namespaces for persistent OAuth state storage across Worker instances
[[kv_namespaces]]
binding = "OAUTH_STATE_KV"
id = "87dc97b9369d46c7b74be662340dbd2f"

[[kv_namespaces]]
binding = "OAUTH_CLIENTS_KV"
id = "a5eef68d5e2b4997aed8b603b48cae14"

[[kv_namespaces]]
binding = "CREDENTIALS_KV"
id = "a49d2dc99f70455abb135787b55d5991"

# Required secrets (set via `wrangler secret put ...`):
#   AUTH_ENCRYPTION_KEY  → Base64 master secret used to derive per-grant AES keys
#   AUTH_SESSION_SECRET  → HMAC secret for session/CSRF signing
#   AUTH_JWT_SECRET      → HMAC secret for MCP access/refresh JWTs
#   AUTH_CLIENTS_JSON    → JSON array describing allowed OAuth clients
# Example:
#   npx wrangler secret put AUTH_ENCRYPTION_KEY
#   npx wrangler secret put AUTH_SESSION_SECRET
#   npx wrangler secret put AUTH_JWT_SECRET
#   npx wrangler secret put AUTH_CLIENTS_JSON
